---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.13.1には、新しい機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.13.1の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.13.1には、新しい機能拡張が含まれています。

その他の機能と拡張機能も、最新バージョンのBlueXPで導入されました。を参照してください https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^] を参照してください。



== 9.13.1 P11（2024年10月14日）

すべてのクラウドプロバイダのCloud Volumes ONTAPで、9.13.1 P11パッチが利用できるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P11["P11パッチで修正されたバグの一覧を表示する"^] （NetAppサポートサイトへのログインが必要です）。



== 9.13.1 P10（2024年8月8日）

すべてのクラウドプロバイダのCloud Volumes ONTAPで、9.13.1 P10パッチが利用できるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P10["P10パッチで修正されたバグの一覧を表示する"^] （NetAppサポートサイトへのログインが必要です）。



== 9.13.1 P9（2024年5月22日）

すべてのクラウドプロバイダを対象に、Cloud Volumes ONTAP 9.13.1 P9パッチがリリースされました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P9["P9パッチで修正されたバグのリストを表示する"^] （NetApp Support Siteへのログインが必要です）。



== 9.13.1 P8（2024年4月18日）

すべてのクラウドプロバイダを対象に、Cloud Volumes ONTAP 9.13.1 P8パッチが提供されるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P8["P8パッチで修正されたバグのリストを表示する"^] （NetApp Support Siteへのログインが必要です）。



== 9.13.1 P7（2024年4月1日）

すべてのクラウドプロバイダを対象に、Cloud Volumes ONTAP 9.13.1 P7パッチが提供されるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P7["P7パッチで修正されたバグのリストを表示する"^] （NetApp Support Siteへのログインが必要です）。



== 9.13.1 P6（2024年2月5日）

すべてのクラウドプロバイダを対象に、Cloud Volumes ONTAP 9.13.1 P6パッチが提供されるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P6["P6パッチで修正されたバグのリストを表示する"^] （NetApp Support Siteへのログインが必要です）。



== 9.13.1 P4（2023年12月8日）

すべてのクラウドプロバイダを対象に、Cloud Volumes ONTAP 9.13.1 P4パッチが提供されるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P4["P4 パッチで修正されたバグのリストを確認します"^] （NetApp Support Siteへのログインが必要です）。



== 9.13.1 P2および9.13.1 P3（2023年10月20日）

バージョン3.9.26以降を実行しているコネクタを使用している場合、すべてのクラウドプロバイダのCloud Volumes ONTAPで、9.13.1 P2および9.13.1 P3のパッチが利用できるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P3["P3パッチで修正されたバグのリストを表示する"^] （NetApp Support Siteへのログインが必要です）。
* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P2["P2パッチで修正されたバグの一覧を表示する"^] （NetApp Support Siteへのログインが必要です）。




== 9.13.1 P1（2023年10月3日）

バージョン3.9.26以降を実行しているコネクタを使用している場合、すべてのクラウドプロバイダでCloud Volumes ONTAP 9.13.1 P1パッチを利用できるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P1["P1パッチで修正されたバグの一覧を表示する"^] （NetApp Support Siteへのログインが必要です）。



== 9.13.1 GA（2023年7月26日）

Cloud Volumes ONTAP 9.13.1のGeneral Availabilityリリースが、AWS、Azure、Google Cloudで利用できるようになりました。



== 9.13.1 RC1（2023年6月26日）

Cloud Volumes ONTAP 9.13.1のRelease Candidate 1が、AWS、Azure、Google Cloudで利用できるようになりました。

FabricPoolのパフォーマンスがいくつか改善されると、Cloud Volumes ONTAPの階層化データに影響する可能性があります。

.シーケンシャルリードの速度と階層化の向上
FabricPoolでの読み取りパフォーマンスと階層化のスループットが向上したため、オンプレミスのオブジェクトストアでのや `PUT`の処理率が高くなる可能性があります `GET`。シームレスなパフォーマンスを実現するための十分なパフォーマンスヘッドルームを確保します。

.積極的な先読み機能
FabricPoolの機能を使用する `Aggressive Readahead`と、ファイルレベルでの読み取り処理が増加し、パブリッククラウドでの読み取りコストとメモリ利用率が上昇する可能性があります。

.Cloud Write機能
NFSクライアントからFabricPoolの大容量階層に直接書き込むことができます。この機能には一定の制限があるため、注意して使用してください。たとえば、SnapMirrorなどの通常のONTAPトラフィックにクラウド書き込みNFSトラフィックが追加されると、SnapMirrorの全体的な目標復旧時点（RPO）と目標復旧時間（RTO）が影響を受ける可能性があります。



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]。



=== サポートされているアップグレードパス

Cloud Volumes ONTAP 9.12.1および9.13.0リリースから9.13.1にアップグレードできます。BlueXPでは、対象となるCloud Volumes ONTAP システムをこのリリースにアップグレードするように求められます。



=== 必要なコネクタのバージョン

新しいCloud Volumes ONTAP 9.13.1システムを導入し、既存のシステムを9.13.1にアップグレードするには、BlueXP Connectorのバージョン3.9.26以降が実行されている必要があります。


TIP: コネクタの自動アップグレードはデフォルトで有効になっているため、最新バージョンを実行する必要があります。



=== ダウンタイム

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。




=== C4、M4、およびR4のインスタンスはサポートされなくなりました

AWSでは、C4、M4、およびR4 EC2インスタンスタイプはCloud Volumes ONTAP でサポートされなくなりました。C4、M4、またはR4インスタンスタイプで実行されている既存のシステムがある場合は、C5、m5、またはr5インスタンスファミリーでインスタンスタイプに変更する必要があります。インスタンスタイプを変更するまで、このリリースにアップグレードすることはできません。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP のEC2インスタンスタイプを変更する方法について説明します"^]。

を参照してください link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["ネットアップサポート"^] これらのインスタンスタイプの可用性とサポート終了の詳細については、を参照してください。
